
#include "ErrorsProcessing.h"
#include "constants.h"
const char* CAN_NOT_LOAD_INDEX_FILE_ERROR_TEXT = "CAN'T LOAD INDEX FILE";

const char* CAN_NOT_LOAD_FREE_SPACES_FILE_ERROR_TEXT = "CAN'T LOAD FREE SPACES FILE";

const char* CAN_NOT_LOAD_AUTHORS_FILE_ERROR_TEXT = "CAN'T LOAD AUTHORS FILE";

const char* CAN_NOT_LOAD_BOOKS_FILE_ERROR_TEXT = "CAN'T LOAD BOOKS FILE";

const char* CAN_NOT_FIND_AUTHOR_ERROR_TEXT = "CAN'T FIND AUTHOR WITH SPECIFIED ID";

const char* CAN_NOT_FIND_BOOK_ERROR_TEXT = "CAN'T FIND BOOK WITH SPECIFIED ID";

map<int, const char*> ERRORS_MAP = {
	{CAN_NOT_LOAD_INDEX_FILE_ERROR_CODE, CAN_NOT_LOAD_INDEX_FILE_ERROR_TEXT},
	{CAN_NOT_LOAD_FREE_SPACES_FILE_ERROR_CODE, CAN_NOT_LOAD_FREE_SPACES_FILE_ERROR_TEXT},
	{CAN_NOT_LOAD_AUTHORS_FILE_ERROR_CODE, CAN_NOT_LOAD_AUTHORS_FILE_ERROR_TEXT},
	{CAN_NOT_LOAD_BOOKS_FILE_ERROR_CODE, CAN_NOT_LOAD_BOOKS_FILE_ERROR_TEXT},
	{CAN_NOT_FIND_AUTHOR_ERROR_CODE, CAN_NOT_FIND_AUTHOR_ERROR_TEXT},
	{CAN_NOT_FIND_BOOK_ERROR_CODE, CAN_NOT_FIND_BOOK_ERROR_TEXT}
};

void printError(int error) {
	cout << "ERROR " << error << ": " << ERRORS_MAP[error] << endl;
}